services:
  - type: web
    name: educollege
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install --prefix server && npm install --include=dev --prefix client && npm run build --prefix client
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
